### PR TITLE
:tada::pencil: build out basic structure

### PR DESCRIPTION
**Pull request by jgiven100**
Starting to work on building out the benchmark repo. 

Wanted to make sure this structure is what we were all thinking before going too far.

Here are the highlights:
* Folders here match the offered `"Input Files"` types in our [wiki](https://github.com/geomechanics/mpm/wiki).
* Examples are broken into "use cases" and "validation"

I think we can figure out the structure for the actual exmaple in the next PR.

### CODE REVIEW

**Review by bodhinandach — APPROVED** [review]
Let's go with this for now! Thank you! I will move the nightly benchmark test in the main repo to this repo. 

Some thoughts: do we want to copy some tests from the main CB-Geo repo branch and reformat them in this style?

**Comment by jgiven100** [comment]
Off the top of my head, I think we're going to want like the `hydrostatic column` and `axial stress`. But I'll have to look more closely at the CB-Geo to see which ones to grab

**Comment by jgiven100** [comment]
@bodhinandach do you want to wait until the nightly test is set up before merging anything?

**Comment by bodhinandach** [comment]
No we can nerge this. I will make a follow up PR. Thanks!

**Pull request merged**
